const CLUB_TIME_ZONE = "Asia/Kolkata";
const FEE_DIGITAL_START_MONTH = "2026-06";
const FEE_FINANCIAL_YEAR_START_MONTH = 6;
const INITIAL_MONTHLY_FEE = 1500;
const MAX_ADVANCE_PAYABLE_MONTHS = 12;

export {
  CLUB_TIME_ZONE,
  FEE_DIGITAL_START_MONTH,
  FEE_FINANCIAL_YEAR_START_MONTH,
  INITIAL_MONTHLY_FEE,
  MAX_ADVANCE_PAYABLE_MONTHS,
};
